# Generated by Django 5.0.3 on 2024-05-07 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_user_profile_rename_user_listing_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.profile', verbose_name='user_profile'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile', verbose_name='user_profile'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vehicle', verbose_name='vehicle_profile'),
        ),
    ]
