# Generated by Django 5.0.3 on 2024-05-09 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_vehicle_price_alter_listing_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
