# Generated by Django 5.0.3 on 2024-05-14 23:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_listing_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="account_type",
            field=models.CharField(
                choices=[("Rentor", "Rentor"), ("Rentee", "Rentee")],
                default="",
                max_length=6,
            ),
        ),
    ]
