# Generated by Django 5.0.3 on 2024-05-15 00:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_profile_account_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="account_type",
            new_name="groups",
        ),
    ]
