# Generated by Django 5.0.3 on 2024-05-21 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_alter_vehicle_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="vehicle_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
