# Generated by Django 5.0.3 on 2024-05-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_vehicle_vehicle_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="is_rented",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="vehicle_image",
            field=models.ImageField(
                blank=True, default="car.png", null=True, upload_to=""
            ),
        ),
    ]
