# Generated by Django 5.0.3 on 2024-05-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_vehicle_is_rented_alter_vehicle_vehicle_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="is_rented",
        ),
        migrations.AddField(
            model_name="listing",
            name="is_rented",
            field=models.BooleanField(default=False),
        ),
    ]
