# Generated by Django 5.0.3 on 2024-05-23 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0014_remove_vehicle_is_rented_listing_is_rented"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="rentee_profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rentee",
                to="app.profile",
            ),
        ),
    ]
